[2023-04-20T13:51:02.836+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: Training_saving_model.training_saving_model_task manual__2023-04-20T13:50:48.612985+00:00 [queued]>
[2023-04-20T13:51:02.847+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: Training_saving_model.training_saving_model_task manual__2023-04-20T13:50:48.612985+00:00 [queued]>
[2023-04-20T13:51:02.848+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-04-20T13:51:02.848+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2023-04-20T13:51:02.849+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-04-20T13:51:02.879+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): training_saving_model_task> on 2023-04-20 13:50:48.612985+00:00
[2023-04-20T13:51:02.883+0000] {standard_task_runner.py:55} INFO - Started process 45836 to run task
[2023-04-20T13:51:02.884+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2023-04-20T13:51:02.890+0000] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'Training_saving_model', 'training_saving_model_task', 'manual__2023-04-20T13:50:48.612985+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/dags.py', '--cfg-path', '/tmp/tmp9pd8kcmj']
[2023-04-20T13:51:02.892+0000] {standard_task_runner.py:83} INFO - Job 3: Subtask training_saving_model_task
[2023-04-20T13:51:02.963+0000] {task_command.py:388} INFO - Running <TaskInstance: Training_saving_model.training_saving_model_task manual__2023-04-20T13:50:48.612985+00:00 [running]> on host 57659a2d2b4a
[2023-04-20T13:51:03.049+0000] {taskinstance.py:1507} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=admin@admin.be
AIRFLOW_CTX_DAG_OWNER=Romain
AIRFLOW_CTX_DAG_ID=Training_saving_model
AIRFLOW_CTX_TASK_ID=training_saving_model_task
AIRFLOW_CTX_EXECUTION_DATE=2023-04-20T13:50:48.612985+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-20T13:50:48.612985+00:00
[2023-04-20T13:51:03.051+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: model_train_saving() missing 2 required positional arguments: 'als' and 'data_sdf'
[2023-04-20T13:51:03.056+0000] {taskinstance.py:1318} INFO - Marking task as UP_FOR_RETRY. dag_id=Training_saving_model, task_id=training_saving_model_task, execution_date=20230420T135048, start_date=20230420T135102, end_date=20230420T135103
[2023-04-20T13:51:03.092+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 3 for task training_saving_model_task (model_train_saving() missing 2 required positional arguments: 'als' and 'data_sdf'; 45836)
[2023-04-20T13:51:03.139+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-04-20T13:51:03.160+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
